format_version: 10
pipelines:
  promethus:
    group: Tools
    materials:
      git-1ab79a5:
        git: https://github.com/devopsnagesha/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Ansible:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            tasks:
            - exec: {command: ansible-playbook, arguments: [ "-i", "prometheus.angadicnc.online", "tools.yml","-e", "tool_name=prometheus","-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}


